apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-products-deployment
  namespace: event-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      transaction-products: web
  template:
    metadata:
      labels:
        transaction-products: web
    spec:
      containers:
        - name: transaction-products
          image: transaction-products
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-config
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-release-mongodb
                  key: mongodb-root-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-config
                  key: authenticationdatabase
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-shop-db
                  key: host
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-products-service
  namespace: event-shop
spec:
  type: NodePort
  selector:
    transaction-products: web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
